-- CURRENT_DATE
-- PostgreSQL, MySQL
SELECT CURRENT_DATE;

-- SQLServer
-- CURRENT_TIMESTAMPをCASTで日付型に変換
SELECT CAST(CURRENT_TIMESTAMP AS DATE) AS CUR_DATE;

-- Oracle
SELECT CURRENT_DATE
FROM dual;

-- DB2
SELECT CURRENT DATE
FROM SYSIBM.SYSDUMY1;


-- CURRENT_TIME
SELECT CURRENT_TIME;

-- SQLServer
-- CURRENT_TIMESTAMPをCASTで時刻型に変換
SELECT CAST(CURRENT_TIMESTAMP AS TIME) AS CUR_TIME;

-- Oracle
SELECT CURRENT_TIMESTAMP
FROM dual;

-- DB2
SELECT CURRENT TIME
FROM SYSIBM.SYSDUMY1;


-- CURRENT_TIMESTAMP
-- SQLServer, PostgreSQL, MySQL
SELECT CURRENT_TIMESTAMP;

-- Oracle
SELECT CURRENT_TIMESTAMP
FROM dual;

-- DB2
SELECT CURRENT TIMESTAMP
FROM SYSIBM.SYSDUMY1;


-- EXTRACT
-- PostgreSQL, MySQL
SELECT CURRENT_TIMESTAMP,
    EXTRACT(YEAR   FROM CURRENT_TIMESTAMP) AS year,
    EXTRACT(MONTH  FROM CURRENT_TIMESTAMP) AS month,
    EXTRACT(DAY    FROM CURRENT_TIMESTAMP) AS day,
    EXTRACT(HOUR   FROM CURRENT_TIMESTAMP) AS hour,
    EXTRACT(MINUTE FROM CURRENT_TIMESTAMP) AS minute,
    EXTRACT(SECOND FROM CURRENT_TIMESTAMP) AS second;

-- SQLServer
SELECT CURRENT_TIMESTAMP,
    DATEPART(YEAR   FROM CURRENT_TIMESTAMP) AS year,
    DATEPART(MONTH  FROM CURRENT_TIMESTAMP) AS month,
    DATEPART(DAY    FROM CURRENT_TIMESTAMP) AS day,
    DATEPART(HOUR   FROM CURRENT_TIMESTAMP) AS hour,
    DATEPART(MINUTE FROM CURRENT_TIMESTAMP) AS minute,
    DATEPART(SECOND FROM CURRENT_TIMESTAMP) AS second;

-- Oracle
SELECT CURRENT_TIMESTAMP,
    EXTRACT(YEAR   FROM CURRENT_TIMESTAMP) AS year,
    EXTRACT(MONTH  FROM CURRENT_TIMESTAMP) AS month,
    EXTRACT(DAY    FROM CURRENT_TIMESTAMP) AS day,
    EXTRACT(HOUR   FROM CURRENT_TIMESTAMP) AS hour,
    EXTRACT(MINUTE FROM CURRENT_TIMESTAMP) AS minute,
    EXTRACT(SECOND FROM CURRENT_TIMESTAMP) AS second
FROM DUAL;

-- DB2
SELECT CURRENT_TIMESTAMP,
    EXTRACT(YEAR   FROM CURRENT_TIMESTAMP) AS year,
    EXTRACT(MONTH  FROM CURRENT_TIMESTAMP) AS month,
    EXTRACT(DAY    FROM CURRENT_TIMESTAMP) AS day,
    EXTRACT(HOUR   FROM CURRENT_TIMESTAMP) AS hour,
    EXTRACT(MINUTE FROM CURRENT_TIMESTAMP) AS minute,
    EXTRACT(SECOND FROM CURRENT_TIMESTAMP) AS second
FROM SYSIBM.SYSDUMMY1;
